### ISSUE TITLE
Get all assignments flag

### ISSUE THREAD

**Issue by kallepronk** [Typiqally/epsilon#17]
Can there be a few flags to specify more or other assignments? It would be nice to be able to get assignments with certain statuses or a getall function for assignments that have not been graded.

**Comment by NealGeilen** [comment]
To specify. 

You would like to see a filter on the status of KPIs that are listed in the exports?
Whether the KPIs are mastered or not

**Comment by Typiqally** [comment]
@kallepronk, can you clarify any time soon? Otherwise, I will close this issue.
