### ISSUE TITLE
Wiki typo startup command

### ISSUE THREAD

**Issue by Maxvanhattum** [Typiqally/epsilon#18]
at: https://github.com/Typiqally/epsilon/wiki/How-to-use#5-export-your-kpis 
To export your KPIs, you need to execute the Epsilon.Cli.exe file within a command prompt. .\Epsilon.Cli.exe --Export:Formats:0 CSV
CSV should be lowercase eg: csv. The same goes for XLS, must be xls.

**Comment by Typiqally** [comment]
This has already been fixed in the upcoming patch #20
