### ISSUE TITLE
Optimizing release builds 

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/epsilon#23]
At the moment the releases contain multiple files. 
Only the `Epsilon.Cli.exe` and the `appsettings.json` are file that the user interacts with.
Seeking for an solution that will reduce the included files.

**Comment by Typiqally** [comment]
These options should be enabled and will generate a single file executable. The included .pdb files can be removed, they are not necessary for running the application.

![image](https://user-images.githubusercontent.com/12190745/173759441-2b353bff-33be-49f2-806d-054d542e4362.png)

**Comment by NealGeilen** [comment]
The release we have at the moment already works without the `.pdb` files. 
Therefore the CD pipeline just need to be cleaned up

**Comment by Typiqally** [comment]
Yeah just need to remove the .pdb files
