### ISSUE TITLE
Improve release assets

### ISSUE THREAD

**Issue by Typiqally** [Typiqally/epsilon#26]
Epsilon binaries are currently published as zip archives. These ZIP archives require an extra extraction step before Epsilon can be used. This can be greatly inconvenient, especially when trying to update to the latest version of Epsilon.

One proposed solution to this issue is to release the binary without compressing it into a zip archive. This causes one  issue, which is the missing configuration file. It may be possible to resolve this issue by creating a default configuration file when one does not already exist.

**Comment by NealGeilen** [comment]
> It may be possible to resolve this issue by creating a default configuration file when one does not already exist.

At of this moment, I find that this will not work, The whole point of having the `appsettings.json` is to store the course Id and the API token. Yes, it can be made that the document will be generated. But the settings will need to be given by the user for the application to function. 
With this proposal, the user will need to start the application for the generation of the settings file. Then close the application to fill in the required settings and start then the application again. 

I would suggest closing this issue. People that will use the application are technically skilled to overcome this inconvenient circumstance.

**Comment by Typiqally** [comment]
I suggest we release the project binaries, not as a zip file, just as the executable. And supplementary a template of the appsettings.json.

**Comment by NealGeilen** [comment]
When resolving this issue in development. It has become clear that GitHub forces the use of a Zip files. As can be seen in this [run](https://github.com/Typiqally/epsilon/actions/runs/3399535552) The executable file is asked for. Not a directory.  Still, the artefacts are presented within a zip file. 

Therefore I am closing this issue, This is how GitHub deals with artifacts apparently

**Comment by Typiqally** [comment]
Releases have nothing to do with artifacts
