### ISSUE TITLE
As a developer, I want to use a standardised Office SDK, so that I don't need multiple overlapping libraries to generate Office documents

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/epsilon#42]
At this moment there are multiple libraries used to create export files. 
[Open_XML-SDK](https://github.com/OfficeDev/Open-XML-SDK) has support for, word documents and spreadsheets. It is an open-source lib created by the Office developer team from Microsoft.

This is for now maybe a nice to have.  But with more features, this lib has. It can become a need when more features are required

**Comment by Typiqally** [comment]
Since it's from Microsoft can you confirm that it works on Linux? I can check macOS.

**Comment by NealGeilen** [comment]
There are no items listed on what OS systems are supported, but reading [this](https://github.com/OfficeDev/Open-XML-SDK/issues/100#issuecomment-293019085) issue its worth trying if it works in our context.

**Comment by Typiqally** [comment]
Just wondering if they use Windows specific libraries under the curtains, just like the other Excel libraries we tried back in the day. Some are even dependent on the Office dlls on Windows. But definitely worth a try.

**Comment by NealGeilen** [comment]
So, I wanted to make a prototype today. Just to see how it works. And I stumbled across [this](https://learn.microsoft.com/en-us/office/open-xml/what-s-new-in-the-open-xml-sdk#system-requirements)  It has indeed an official support list. So I have the feeling the beforementioned issue is unofficial support for Linux

**Comment by Typiqally** [comment]
If you make a small prototype I can test it on macOS. Doesn't have to be in this repo you can just make a standalone app and send it as a ZIP to me. Whatever is easier for you.
