### ISSUE TITLE
As a student using Canvas, I want to experience fast page load times and quick access to frequently used data, so that I can see my competence document without any unnecessary delay or frustration.

### ISSUE THREAD

**Issue by Typiqally** [Typiqally/epsilon#53]
Fetching results from Canvas takes a long time, while not always being necessary. If I perform a run and decide I want to export it in a different format, I have to wait for the requests to finish again. This even though nothing was probably changed in the last 5 minutes or maybe even an hour. Therefore, I think we should implement an expiration policy on the Canvas results and apply caching on it.

For example, if we perform a run and the results are not older than an hour, then we reuse them. If they are older, we fetch the latest version from Canvas. This can also be overridden by using a `--no-cache` parameter option for example.

Maybe it's not necessary for now, since runs are not very frequent at the moment. For the future this might change however, if we create an online webpage which can be accessed by peer students and teachers.

**Comment by honzafojtik** [comment]
- Edit, this is steering towards being more of NFR
