### ISSUE TITLE
As a student, I want to be able to interact with Epsilon through an LTI, so that I don't have to install and use the CLI

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/epsilon#57]
Researching the possibilities to implement Epsilon inside Canvas with the help of an LTI:

- [ ] Where should cache be placed? In API as session or in browser cookie?
- [ ] What kind of access do we require, are LTI resources sufficient or do we need specific Canvas resources?

**Comment by honzafojtik** [comment]
- Rewrite, less technical and more explanatory
