### ISSUE TITLE
Return processed data from exporters

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/epsilon#60]
Currently, the exporters return void when finished. This is something that is not sustainable when moving to an API application. 

The export functions will need to return a value that will represent the contents or the exported file itself. 
Importantly it can not be a string representing the location of the file.

**Comment by HansenSven** [comment]
Hi @NealGeilen, would it be an idea for me to also address this along with the unit testing strategy ticket I'm working on? This would allow me to directly write unit tests for the exporters method in the set up test project.

**Comment by NealGeilen** [comment]
> Hi @NealGeilen, would it be an idea for me to also address this along with the unit testing strategy ticket I'm working on? This would allow me to directly write unit tests for the exporters method in the set up test project.

Yes is a good idea.
