### ISSUE TITLE
As a project owner, I want to write a project initiation document (PID) to ensure that all stakeholders have a shared understanding of the project objectives, scope, and deliverables, so that we can effectively plan and execute the project.

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/epsilon#61]
Adjust the project plan to include the broader scope of the project 

- general idea
- research questions
- list problems

**Comment by honzafojtik** [comment]
- Split up to several tasks such:
1. PID (means of communication, VCS, etc.)
2. Make a technical document with coding guidelines with quality criteria that are specific to the code such as unit testing
