### ISSUE TITLE
User interface / production build

### ISSUE THREAD

**Issue by NealGeilen** [Typiqally/epsilon#8]
The creation of a production build version of the application. 
The production build can be a user interface or a CLI application. 

The application will need a workflow

1. Give access token
2. Select the personal course from a list that is given 
3. Collect KPIs
4. Choose an export format

What will it be? User interface or CLI?

**Comment by Typiqally** [comment]
One of the wishes from Eric Slaats was to integrate Epsilon into Canvas, where it will be a replacement for the performance dashboard.
